export const addonsType = {
  "LO1": "Docking Station:",
  "LO2": "Keyboard:",
  "LO3": "Software Bundle:",
  "LO4": "Monitor:",
  "LO5": "Speakers:",
  "LO6": "Optical Drive:",
  "LO7": "Security-Enabled Features:",
  "LO8": "Hard Drive Upgrade:",
  "LO9": "Warranty (Optional):",
  "LO10": "Warranty (Optional):",
  "LO11": "Decaling (Pre-Supplied):",
  "LO12": "Decaling (Provided With Order):",
  "LO13": "Add-On Warranty I:",
  "LO14": "Add-On Warranty II:",
  "LO15": "Add-On Warranty III:",
  "LO16": "Battery Size:",
  "LO17": "Platform Integrity Upgrade:",
  "LO18": "Imaging:",
  "LO19": "Imaging:",
  "LO20": "Alternative CPU:",
  "LO21": "Graphics Card:",
  "LO22": "Display Upgrade:",
  "DO1": "Software Bundle:",
  "DO2": "Monitor:",
  "DO3": "Speakers:",
  "DO4": "Graphics Card Upgrade:",
  "DO5": "Security-Enabled Features:",
  "DO6": "Optical Drive:",
  "DO7": "Disk Drive (Primary):",
  "DO8": "Memory Upgrade:",
  "DO9": "Warranty:",
  "DO10": "Warranty:",
  "DO11": "Decaling (Pre-Supplied):",
  "DO12": "Decaling (Provided With Order):",
  "DO13": "Add-On Warranty I:",
  "DO14": "Imaging:",
  "DO15": "Imaging:",
  "DO16": "Form Factor:",
  "DO17": "Alternative CPU:",
  "MLO1": "CPU Upgrade I (Optional):",
  "MLO2": "CPU Upgrade II (Optional):",
  "MLO3": "Internal Storage Upgrade I (Optional):",
  "MLO4": "Internal Storage Upgrade II (Optional):",
  "MLO5": "Graphics Upgrade I:",
  "MLO6": "Software Bundle:",
  "MLO7": "External Monitor:",
  "MLO8": "Accessory - Networking:",
  "MLO9": "Accessory - Display Adapters:",
  "MLO10": "Accessory - Display Cables:",
  "MLO11": "Accessory - Keyboard:",
  "MLO12": "Accessory - Mouse:",
  "MLO13": "Accessory - Trackpad:",
  "MLO14": "Speakers:",
  "MLO15": "Optical Drive:",
  "MLO16": "Warranty Upgrade I (Optional):",
  "MLO17": "Warranty Upgrade II (Optional):",
  "MLO18": "RAM Upgrade:",
  "MDO1": "CPU Upgrade I (Optional):",
  "MDO2": "CPU Upgrade II (Optional):",
  "MDO3": "RAM Upgrade I (Optional):",
  "MDO4": "RAM Upgrade II (Optional):",
  "MDO5": "Internal Storage Upgrade I (Optional):",
  "MDO6": "Internal Storage Upgrade II (Optional):",
  "MDO7": "Warranty Upgrade I (Optional):",
  "MDO8": "Warranty Upgrade II (Optional):",
  "MDO9": "Software Bundle:",
  "MDO10": "External Monitor:",
  "MDO11": "Accessory - Display Adapters:",
  "MDO12": "Accessory - Display Cables:",
  "MDO13": "Imaging:",
  "MDO14": "Imaging:",
  "MDO15": "Speakers:",
  "MDO16": "Optical Drive:",
  "TO1": "Docking Station:",
  "TO2": "Keyboard:",
  "TO3": "Software Bundle:",
  "TO4": "Monitor:",
  "TO5": "Speakers:",
  "TO6": "Optical Drive:",
  "TO7": "Security-Enabled Features:",
  "TO8": "Hard Drive Upgrade:",
  "TO9": "Imaging:",
  "TO10": "Imaging:",
  "TO11": "Alternative CPU:",
  "TO12": "Graphics Card:",
  "TO13": "RAM Upgrade:",
  "TO14": "4 Year Warranty (Optional):",
  "TO15": "5 Year Warranty (Optional):",
  "UNDEFINED": "Optional:"
}